# Generated by Django 2.1 on 2020-01-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200121_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hashTag',
            field=models.ManyToManyField(blank=True, to='event.HashTag'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
