# Generated by Django 2.1 on 2020-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200121_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
